export const RECEIVE_JDC_RESILT = 'RECEIVE_JDC_RESILT';

export const RECEIVE_JDC_CORE = 'RECEIVE_JDC_CORE';

export const RECEIVE_JDC_SUPPORT = 'RECEIVE_JDC_SUPPORT';

export const RECEIVE_JDC_GAIN = 'RECEIVE_JDC_GAIN';

export const RECEIVE_JDC_GAIN_EXTRA = 'RECEIVE_JDC_GAIN_EXTRA';

// 修改人物属性
export const RECEIVE_JDC_CHARACTER_CHANGE = 'RECEIVE_JDC_CHARACTER_CHANGE';
export const RESET_JDC_CHARACTER_CHANGE = 'RESET_JDC_CHARACTER_CHANGE';
export const REPLEASE_JDC_CHARACTER_ATTRIBUTES = 'REPLEASE_JDC_CHARACTER_ATTRIBUTES';

export const RECEIVE_JDC_TARGET = 'RECEIVE_JDC_TARGET';
export const RECEIVE_JDC_CW_TIMES = 'RECEIVE_JDC_CW_TIMES';
